### Import the necessary libraries

In [0]:
from numpy import array
# import one-hot-encoding from keras 
# import padding helper function from keras
# import sequential 
# import Dense from keras 
# import flatten helper from keras
# import embedding helper from keras

### Define the corpus

In [0]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# Add more data if you want to experiment

### Define the labels

In [0]:
labels = array([1,1,1,1,1,0,0,0,0,0])
# Adjust this accordingly to the documents in the corpus

### One-hot encoding of corpus

In [0]:
vocab_size = 50
encoded_docs = None # Hint: Use one-hot-encoding function
print(encoded_docs)

[[27, 2], [26, 4], [8, 47], [34, 4], [37], [26], [48, 47], [41, 26], [48, 4], [45, 7, 2, 17]]


### Padding documents to a desired max_length

In [0]:
max_length = 4
padded_docs = None # Hint: Use padding helper function from the above import
print(padded_docs)

[[27  2  0  0]
 [26  4  0  0]
 [ 8 47  0  0]
 [34  4  0  0]
 [37  0  0  0]
 [26  0  0  0]
 [48 47  0  0]
 [41 26  0  0]
 [48  4  0  0]
 [45  7  2 17]]


### Define the model

In [0]:
model = None # Hint: Add Sequential
model.add(None) # Add Embedding layer
model.add(None) # Flatten the layer
model.add(None) # Add Dense layer

### Compiling the model

In [0]:
# Define Adam optimizer, loss function for two-class classification, accuracy metric
model.compile(None)
# Experiment with multiple parameters of these values

### Summarize the model

In [0]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_3 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


### Build the model

In [0]:
# Fit the model with number of epochs = 50 and pass input and output
model.fit(None)

### Evaluating the model

In [0]:
loss, accuracy = model.evaluate(None)
print('Accuracy: %f' % (accuracy*100))