### Import the necessary libraries

In [1]:
from numpy import array, asarray, zeros
from keras.preprocessing.text import one_hot, Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


### Define the corpus

In [2]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

### Define the labels

In [3]:
labels = array([1,1,1,1,1,0,0,0,0,0])

### Tokenizer

In [4]:
t = None # Hint: Use Tokenizer class
t.None # Use an appropriate function to fit text
vocab_size = len(t.word_index) + 1

### Integer encode the documents

In [5]:
encoded_docs = t.None
print(encoded_docs)

[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]


### Padding documents to a desired max_length

In [6]:
max_length = 4
padded_docs = None
print(padded_docs)

[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


### Load the GloVe Embedding into memory

In [7]:
embeddings_index = dict()
f = open('glove.6B.50d.txt')
for line in f: # Hint: Look at txt file and figure out a way to split the coefficients and build a dictionary
    None
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 400000 word vectors.


### Create Embedding matrix for the custom dataset

In [8]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 50))
for word, i in t.word_index.items():
    embedding_vector = None
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

### Define the Embedding layer

In [9]:
e = Embedding(None) # Hint: Use trainable=False

### Define the model

In [10]:
model = None
model.add(e)
model.add(None)
model.add(Dense(1, activation='sigmoid'))

### Compiling the model

In [11]:
model.compile(None)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


### Summarize the model

In [12]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 50)             750       
_________________________________________________________________
flatten_1 (Flatten)          (None, 200)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 201       
Total params: 951
Trainable params: 201
Non-trainable params: 750
_________________________________________________________________
None


### Build the model

In [13]:
model.fit(None)

### Evaluating the model

In [14]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000
